### ISSUE TITLE
Button Card Template Clarity

### ISSUE THREAD

**Issue by saucedge** [crixle/homeassistant-config#1]
Very impressive setup, I've been playing with bits and pieces to try and port over to my setup.  I'm looking at the light panel and have it functionally working, but I can't for the life of me get the button card templates to do anything.  I notice you have button_card_templates: in your ui-lovelace.yaml file AND in your button_card_templates.yaml file.  I don't see an include for the button_card_templates.yaml in your ui-lovelace.yaml... so I put the templates in the ui-lovealce.yaml file directly.  Let me know if I'm missing something, I'm sure I'm just struggling with templates in general.

**Comment by saucedge** [comment]
I think I had messed something up when trying to eliminate the pop-up browser mod portions.  I've resolved that... but I'm left with everything working except the icon size it annoyingly small.  Where do you define the icon size for the light panel since it doesn't seem to be in the template?

**Comment by crixle** [comment]
I included the templates in the UI and in their own file just to make it easier to isolate for copying, but just take the one called "grid_card" and take out the other template it's calling for. In terms of icon sizing, I'm unsure why they'd be like that. Would you mind showing me what code you have and how they look? You can also just paste the templates inside a normal card but add "type: 'custom:button-card'" to the very top (and an entity ofc)

**Comment by saucedge** [comment]
Thanks for the reply... I'm well aware this is either my own dumb fault or perhaps its a button-card issue, so thanks for taking a peek anyways.  Here's what I'm seeing.... the vertical stack on the right is the functional implementation with a blue icon added to convince myself that the templates were showing up at least partially.  The other cards are were attempts to isolate the behavior but I can't get the size to change in any way.  The yaml is below the image.... thanks again!

![image](https://user-images.githubusercontent.com/52023198/133692008-c342aa4b-89db-49d9-b9de-b6bd904d5f30.png)

ui-lovelace.yaml
```
background: var(--background-image)
title: Home


views:
  - !include ui-lovelace/01_view_controls.yaml
  - !include ui-lovelace/02_view_rooms.yaml
  - !include ui-lovelace/03_view_house.yaml
  - !include ui-lovelace/04_view_security.yaml
  - !include ui-lovelace/05_view_analytics.yaml
  #- !include ui-lovelace/06_view_network.yaml
  - !include ui-lovelace/07_test.yaml

button_card_templates:

  grid_card:
    show_state: true
    size: 40px
    aspect_ratio: 1/1
    tap_action:
      #haptic: light
      action: toggle
    styles:
      card:
        - box-shadow: >-
            rgba(50, 50, 93, 0.25) 0px 6px 12px -2px, rgba(0, 0, 0, 0.3) 0px 3px
            7px -3px
      grid:
        - grid-template-areas: |
            " i . " " n n " " s l "
      img_cell:
        - align-self: start
        - text-align: start
        - display: inline-block
        - padding-left: 10px
      name:
        - justify-self: start
        - padding-left: 10px
        - font-weight: bold
      state:
        - justify-self: start
        - padding-left: 10px
      icon:
        - color: blue
    state:
      - value: 'off'
        styles:
          card:
            - filter: opacity(50%)
          icon:
            - filter: grayscale(100%)
  light:
    # template: popup
    state:
      - value: 'on'
        styles:
          icon:
            - color: var(--button-card-light-color)

  popup:
    hold_action:
      action: fire-dom-event
      browser_mod:
        command: popup
        title: |
          [[[ return entity.attributes.friendly_name; ]]]
        card:
          type: entities
          entities:
            - type: custom:light-popup-card
              entity: |
                [[[ return entity.entity_id ]]]
              icon: none
              fullscreen: false
              brightnessWidth: 130px
              brightnessHeight: 360px
              borderRadius: 2em
              sliderColoredByLight: true
              sliderTrackColor: rgba(25, 25, 25, 0.9)
              displayType: slider
            - type: custom:hui-horizontal-stack-card
              style: |
                #root {
                  justify-content: center;
                  margin-top: 2em;
                }
              cards:
                - type: custom:button-card
                  styles:
                    card:
                      - background: '#d8d9e1'
                  tap_action:
                    action: call-service
                    service: light.turn_on
                    service_data:
                      entity_id: |
                        [[[ return entity.entity_id ]]]
                      color_temp: 153
                  template: color_light
                - type: custom:button-card
                  styles:
                    card:
                      - background: '#d5b08d'
                  tap_action:
                    action: call-service
                    service: light.turn_on
                    service_data:
                      entity_id: |
                        [[[ return entity.entity_id ]]]
                      color_temp: 326
                  template: color_light
            - type: custom:hui-horizontal-stack-card
              style: |
                #root {
                  justify-content: center;
                  margin-bottom: 1em;
                }
              cards:
                - type: custom:button-card
                  styles:
                    card:
                      - background: '#ce944b'
                  tap_action:
                    action: call-service
                    service: light.turn_on
                    service_data:
                      entity_id: |
                        [[[ return entity.entity_id ]]]
                      color_temp: 500
                  template: color_light
                - type: custom:button-card
                  styles:
                    card:
                      - background: >-
                          radial-gradient(circle, rgba(255, 255, 255, 1) 0%,
                          rgba(255, 255, 255, 0) 80%),  conic-gradient(rgb(120,
                          39, 230), rgb(230, 34, 231), rgb(228, 5, 136),
                          rgb(228, 25, 25),  rgb(229, 105, 30), rgb(232, 226,
                          46), rgb(125, 230, 41), rgb(52, 232, 40), rgb(51, 231,
                          92),  rgb(52, 232, 224), rgb(32, 125, 229), rgb(18,
                          39, 229), rgb(120, 39, 230))
                  tap_action:
                    action: fire-dom-event
                    browser_mod:
                      command: popup
                      title: |
                        [[[ return entity.attributes.friendly_name ]]]
                      card:
                        type: custom:light-entity-card
                        entity: |
                          [[[ return entity.entity_id ]]]
                        brightness: true
                        color_temp: true
                        full_width_sliders: false
                        hide_header: true
                        show_slider_percent: true
                        smooth_color_wheel: true
                        persist_features: true
                        consolidate_entities: false
                  template: color_light
  
```

07_test.yaml:
```
title: test
icon: mdi:home-map-marker
badges: []
cards:
  - type: custom:button-card
    entity: light.landing_light_2
    aspect_ratio: 1/1
    size: 50px

  - type: vertical-stack
    cards:

      - type: grid
        square: false
        columns: 3
        cards:
          - type: custom:button-card
            template: 
              - grid_card
              # - light
            entity: light.landing_light_1
          - type: custom:button-card
            template: 
              - grid_card
              # - light
            entity: light.landing_light_2
          - type: custom:button-card
            template: 
              - grid_card
              # - light
            entity: light.landing_light_2
          - type: custom:button-card
            template: 
              - grid_card
              # - light
            entity: light.landing_light_2


  - type: vertical-stack
    cards:
    - type: entities
      style: |
        ha-card {
          background: none;
          box-shadow: none;
          }
      entities:
        - type: custom:paper-buttons-row
          buttons:
            - entity: group.girlsroom
              name: false
              icon: mdi:unicorn
              style:
                button:
                  background: rgba(255,255,255,.1)
                  box-shadow: >
                    {% if is_state('group.girlsroom', 'on') %}

                    0px 8px 15px rgba(0, 0, 0, 0.2), inset 0 0 10px
                    rgba(255,255,255,.5)

                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  border-radius: 50px
                  padding: 20px
                  color: |
                    {% if is_state('group.girlsroom', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              # state_styles:
              #   '#girlsroom':
              #     button:
              #       background: rgba(255,255,255,.5)
              #       box-shadow: 0 0 15px rgba(255,255,255,.6)
              tap_action:
                action: navigate
                navigation_path: '#girlsroom'
              hold_action:
                action: toggle
            - entity: group.cartersroom
              name: false
              icon: mdi:tank
              style:
                button:
                  background: rgba(255,255,255,.1)
                  border-radius: 50px
                  padding: 20px
                  box-shadow: |
                    {% if is_state('group.cartersroom', 'on') %}
                    0px 8px 15px rgba(0, 0, 0, 0.2), inset 0 0 10px rgba(255,255,255,.5)
                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  color: |
                    {% if is_state('group.cartersroom', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              tap_action:
                action: navigate
                navigation_path: '#cartersroom'
              hold_action:
                action: toggle
            - entity: group.playroom
              name: false
              icon: mdi:cards-playing-outline
              style:
                button:
                  background: rgba(255,255,255,.1)
                  border-radius: 50px
                  padding: 20px
                  box-shadow: |
                    {% if is_state('group.playroom', 'on') %}
                      0px 8px 15px rgba(0, 0, 0, 0.2),inset 0 0 10px rgba(255,255,255,.5)
                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  color: |
                    {% if is_state('group.playroom', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              tap_action:
                action: navigate
                navigation_path: '#playroom'
              hold_action:
                action: toggle
            - entity: group.masterbedroom
              name: false
              icon: mdi:bed-king
              style:
                button:
                  background: rgba(255,255,255,.1)
                  border-radius: 50px
                  padding: 20px
                  box-shadow: |
                    {% if is_state('group.masterbedroom', 'on') %}
                      0px 8px 15px rgba(0, 0, 0, 0.2),inset 0 0 10px rgba(255,255,255,.5)
                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  color: |
                    {% if is_state('group.masterbedroom', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              tap_action:
                action: navigate
                navigation_path: '#masterbedroom'
              hold_action:
                action: toggle
      view_layout:
        grid-area: orbs
        place-self: end stretch
    - type: entities
      entities:
        - type: custom:state-switch
          entity: hash
          default: livingarea
          states:
            livingarea:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    size: 40px
                    template:
                      - grid_card
                    entity: light.living_room_floor_lamp
                    name: Reading Lamp
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.living_room_fan_light_2
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.living_room_tv_light  
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.lifx_color_675674 
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.kitchen_cabinet_lights_2  
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.landing
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: switch.living_room_fan_2 
            office:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: group.lighthouses
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: fan.office_fan
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.office
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.office_fan_light
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: switch.office_lamp
            diningroom:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.dining_room_lights_2   
            schoolroom:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.entryway_lights
            girlsroom:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.girls_room_lamp
            cartersroom:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.carters_wall_lights
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.carters_room_lamp
            playroom:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.playroom
            masterbedroom:
              type: custom:mod-card
              card:
                type: grid
                square: false
                columns: 3
                cards:
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.master_fan_light
                  - type: custom:button-card
                    template:
                      - grid_card
                    entity: light.master_fan_switch
      view_layout:
        grid-area: control
        place-self: start stretch
      card_mod:
        style: |
          ha-card {
            border-radius: 30px;
          }
    - type: entities
      style: |
        ha-card {
          background: none;
          box-shadow: none;
          }
      entities:
        - type: custom:paper-buttons-row
          buttons:
            - entity: group.office
              name: false
              icon: mdi:desktop-classic
              style:
                button:
                  background: rgba(255,255,255,.1)
                  box-shadow: >
                    {% if is_state('group.office', 'on') %}

                    0px 8px 15px rgba(0, 0, 0, 0.2), inset 0 0 10px
                    rgba(255,255,255,.5)

                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  border-radius: 50px
                  padding: 20px
                  color: |
                    {% if is_state('group.office', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              # state_styles:
              #   '#livingroom':
              #     button:
              #       background: rgba(255,255,255,.5)
              #       box-shadow: 0 0 15px rgba(255,255,255,.6)
              tap_action:
                action: navigate
                navigation_path: '#office'
              hold_action:
                action: toggle
            - entity: group.livingarea
              name: false
              icon: mdi:sofa
              style:
                button:
                  background: rgba(255,255,255,.1)
                  border-radius: 50px
                  padding: 20px
                  box-shadow: |
                    {% if is_state('group.livingarea', 'on') %}
                    0px 8px 15px rgba(0, 0, 0, 0.2), inset 0 0 10px rgba(255,255,255,.5)
                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  color: |
                    {% if is_state('group.livingarea', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              tap_action:
                action: navigate
                navigation_path: '#livingarea'
              hold_action:
                action: toggle
            - entity: group.schoolroom
              name: false
              icon: mdi:school
              style:
                button:
                  background: rgba(255,255,255,.1)
                  border-radius: 50px
                  padding: 20px
                  box-shadow: |
                    {% if is_state('group.schoolroom', 'on') %}
                      0px 8px 15px rgba(0, 0, 0, 0.2),inset 0 0 10px rgba(255,255,255,.5)
                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  color: |
                    {% if is_state('group.schoolroom', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              tap_action:
                action: navigate
                navigation_path: '#schoolroom'
              hold_action:
                action: toggle
            - entity: group.diningroom
              name: false
              icon: mdi:food-turkey
              style:
                button:
                  background: rgba(255,255,255,.1)
                  border-radius: 50px
                  padding: 20px
                  box-shadow: |
                    {% if is_state('group.diningroom', 'on') %}
                      0px 8px 15px rgba(0, 0, 0, 0.2),inset 0 0 10px rgba(255,255,255,.5)
                    {% else %}
                      0px 8px 15px rgba(0, 0, 0, 0.2);
                    {% endif %}
                  color: |
                    {% if is_state('group.diningroom', 'on') %}
                      white
                    {% else %}
                      rgba(0,0,0,.5)
                    {% endif %}
                icon:
                  '--mdc-icon-size': 40px
              tap_action:
                action: navigate
                navigation_path: '#diningroom'
              hold_action:
                action: toggle
      view_layout:
        grid-area: orbs
        place-self: end stretch
path: test
```
